### ISSUE TITLE
Slideshow invisible

### ISSUE THREAD

**Issue by ThomasA** [damianavila/RISE#240]
I have just installed the latest RISE in a freshly installed Anaconda Python environment. Installation seems to work well, the slideshow button shows up in notebooks, and I can start the slideshow, but: the slideshow is invisible. Content is visible during transitions, but as soon as the transition has stopped, the slide turns blank. Hovering over the page with the mouse reveals that the slide text still seems to be there, but it is invisible.

Steps to reproduce:
- Install fresh Anaconda environment and RISE
  ```bash
  conda create -n test-rise anaconda python=3.5
  source activate test-rise
  conda install -c damianavila82 rise
  ```
- Open this notebook: https://gist.github.com/ThomasA/69290e5a025dbc630c909b5af2ca1eff
  *Very simlpe notebook with a Markdown slide and a code slide*
- Start the slideshow. The slides show the above described behaviour on my computer.

I should note that I have attempted to remove left-overs of previous RISE installs by deleting '\~/.local/share/jupyter/nbextensions/livereveal/' and '\~/.ipython/nbextensions/livereveal'. I do not know if there could be any other left-overs causing trouble somewhere?

**Comment by damianavila** [comment]
Sorry for the delay.

What is the output of `jupyter nbextension list`?

**Comment by mjbright** [comment]
Similar issue today.
A recent install of Anaconda3, I installed RISE using
`conda install -c damianavila82 rise`

I can select "Slideshow" mode enabling the cell toolbar but I don't see the Enter/Exit Live Reveal Slideshow" button in the notebook toolbar (I only see nbpresent buttons).

`> jupyter nbextension list`
```Known nbextensions:
  config dir: /home/mjb/.jupyter/nbconfig
    notebook section
      nbbrowserpdf/index  enabled 
      - Validating: OK
  config dir: /home/mjb/usr/anaconda3/etc/jupyter/nbconfig
    notebook section
      nb_anacondacloud/main  enabled 
      - Validating: OK
      nbpresent/js/nbpresent.min  enabled 
      - Validating: OK
      nbtutor/js/nbtutor.min  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      nb_conda/main  enabled 
      - Validating: OK
    tree section
      nb_conda/tree  enabled 
      - Validating: OK
```

`> jupyter --version
4.2.0
`

**Comment by mjbright** [comment]
OK, problem solved in my case.

I tried
`jupyter-nbextension install rise --py --sys-prefix`
`jupyter-nbextension enable rise --py --sys-prefix`

reloaded my notebook and the RISE button appeared.
and now `jupyter nbextension list` gives

```Known nbextensions:
  config dir: /home/mjb/.jupyter/nbconfig
    notebook section
      nbbrowserpdf/index  enabled 
      - Validating: OK
  config dir: /home/mjb/usr/anaconda3/etc/jupyter/nbconfig
    notebook section
      nbpresent/js/nbpresent.min  enabled 
      - Validating: OK
      nb_anacondacloud/main  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      nbtutor/js/nbtutor.min  enabled 
      - Validating: OK
      rise/main  enabled 
      - Validating: OK
      nb_conda/main  enabled 
      - Validating: OK
    tree section
      nb_conda/tree  enabled 
      - Validating: OK

```

**Comment by damianavila** [comment]
@mjbright did you have any failure message when you install it? The `jupyter-nbextension` commands should not be necessary... the conda package should take care of that...

**Comment by ghislainp** [comment]
I've exactly the same problem, the slideshow starts but the text shows up only during the transition, then it disappear immediately letting a white page.

jupyter 4.3.0


Known nbextensions:
  config dir: /home/me/.jupyter/nbconfig
    notebook section
      usability/toggle_all_line_numbers/main  enabled
      - Validating: OK
      usability/toc2/main  enabled
      - Validating: OK
      usability/limit_output/main  enabled
      - Validating: OK
      usability/autoscroll/main  enabled
      - Validating: OK
      usability/comment-uncomment/main  enabled
      - Validating: OK
      config/config_menu/main  enabled
      - Validating: OK
      usability/hide_input_all/main  enabled
      - Validating: OK
      publishing/printview/main  enabled
      - Validating: OK
      usability/keyboard_shortcut_editor/main  enabled
      - Validating: OK
      usability/search-replace/main  enabled
      - Validating: OK
  config dir: /home/me/anaconda3/etc/jupyter/nbconfig
    notebook section
      rise/main  enabled
      - Validating: OK
      nbextensions_configurator/config_menu/main  enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      contrib_nbextensions_help_item/main  enabled
      - Validating: OK
      jupyter-js-widgets/extension  enabled
      - Validating: OK
    tree section
      nbextensions_configurator/tree_tab/main  enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
      nb_conda/tree  enabled
      - Validating: OK

**Comment by damianavila** [comment]
@ghislainp I would suspect of some kind of interaction with other extensions. Can you try backing up your config at /home/me/.jupyter and install RISE in a new clean environment to see if there is some interaction? Thanks.

**Comment by ghislainp** [comment]
I've tried to remove all the .jupyter and /etc, and I've tried to install a new fresh environment... still the same problem.
BUT
I tried with chromium and it works. The problem is only in firefox.

**Comment by damianavila** [comment]
> I tried with chromium and it works. The problem is only in firefox.

OK... nice to know... which Firefox version is failing for you?

**Comment by ghislainp** [comment]
53.0.3 under linux

**Comment by mhardcastle** [comment]
I also have this problem on firefox (52.3.0, debian stretch); fine on chromium. Old versions of firefox work fine.

**Comment by damianavila** [comment]
> I also have this problem on firefox (52.3.0, debian stretch); fine on chromium. Old versions of firefox work fine.

Thanks for the info!

**Comment by sumendar** [comment]
**slide show button is not displaying in  the toolbar** even after successful installation of RISE in my jupyter environment, please let me know any issue here!

**Comment by damianavila** [comment]
@sumendar, we need more information about your setup. Some questions:

* notebook version?
* browser version?
* can you try hard-reloading your browser (some info here: https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/#.Wnmm25M-dhE, to get rid of the cache)?
* can you try installing in a new environment without other extensions to get rid of possible interferences?

**Comment by damianavila** [comment]
Additionally, do you have any output in the js console? If that is the case, please also report it.

**Comment by sumendar** [comment]
I installed recent anaconda Python 3.6 version,
browser is Google chrome Version 64.0.3282.167 (Official Build) (64-bit) 
and i installed RISE into two different machines, the same problem facing **(slideshow button is not appearing on jupyter notebooks)** ,  also suggest do we have any other way to enable slideshow (shortcut or menu items....etc)

**Comment by damianavila** [comment]
Can you try upgrading the notebook package, or even better, create a new environment and install rise on it. Btw, if you could report what I asked before, it would help. Thanks.

**Comment by reberac** [comment]
Hello,
Same issue for me, the slideshow button was not appearing on jupyter notebook. However, after an upgrade of the notebook package as suggested by Damia, it works, thanks !

**Comment by sumendar** [comment]
yes it works after up-gradation!  but my nbextention icons on toolbar are changed to more descriptive than small icons as shown below 
![screenshot_20180311_200424](https://user-images.githubusercontent.com/8832545/37254705-83c9c45e-2567-11e8-8dd6-2a6907ea20a3.png)

**Comment by damianavila** [comment]
@sumendar, what notebook version and rise version do you have? I would bet you still need to upgrade to the latest notebook version...

**Comment by martindurant** [comment]
Confirmed, the following updates made RISE work for me (py35, osx)
```

    jupyter_client: 4.3.0-py35_0 --> 5.2.2-py35_0
    jupyter_core:   4.3.0-py35_0 --> 4.4.0-py35h4ad9194_0
    notebook:       5.0.0-py35_0 --> 5.4.0-py35_0
    terminado:      0.6-py35_0   --> 0.8.1-py35_1
```
