### ISSUE TITLE
Re-enable shift+enter going to next cell when you exit from RISE

### ISSUE THREAD

**Issue by damianavila** [damianavila/RISE#98]

**Comment by jorisvandenbossche** [comment]
I also noticed this: is it intentional for the live slide show mode? (to prevent jumping to next cells while presenting?)

If so, it is maybe worth adding a note about this in the docs.

**Comment by damianavila** [comment]
Yes, this is on purpose, because going to next cell conflict with the slideshow machinery: there is no problem as long as you go to the next cell from the last cell of the present slide, if that is the case,the notebook goes to the next cell, but not the reveal.js. This could be "potentially" solved in the future but it would need cross communication between IPython and the Reveal.js machinery, a lot of work for a little improvement... so it is far down in my TODO list.

I agree that a note in the README is needed. If you want to give a try with a PR :wink:

**Comment by ruffsl** [comment]
I'm just hitting this issue agian with a current setup.py install with both browsers:
* RISE: commit ddc62ba9abf3cd442b37772c231f80d6fba77814
* Jupyter/IPython:
```condole
$ conda list | grep jupyter
jupyter                   1.0.0                    py35_1  
jupyter-client            4.1.1                     <pip>
jupyter-console           4.1.0                     <pip>
jupyter-core              4.0.6                     <pip>
jupyter_client            4.1.1                    py35_0  
jupyter_console           4.1.0                    py35_0  
jupyter_core              4.0.6                    py35_0  
$ conda list | grep ipython
ipython                   4.1.1                    py35_0  
ipython-genutils          0.1.0                     <pip>
ipython-notebook          4.0.4                    py35_0  
ipython-qtconsole         4.0.1                    py35_0  
ipython_genutils          0.1.0                    py35_0
```
* Conda: 
```command
$ conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : linux-64
        conda version : 3.19.1
  conda-build version : 1.19.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /home/ubuntu/anaconda3  (writable)
  default environment : /home/ubuntu/anaconda3
     envs directories : /home/ubuntu/anaconda3/envs
        package cache : /home/ubuntu/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```
* Firefox: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0)
* Chrome: Version 48.0.2564.82 (64-bit)

**Comment by rsdenijs** [comment]
I am having this issue too. Shift + Enter is not re-enabled when leaving presentaiton mode.

**Comment by damianavila** [comment]
Tested this with notebook 5 and RISE master and I can not see the issue anymore. So closing now. Please reopen if you still see the issue with the latest notebook.

**Comment by ijstokes** [comment]
I am still seeing this issue.  I have RISE installed from master (installed just a few days ago), and notebook 5.0.0 (conda package).  After presenting once with RISE the SHIFT-ENTER key combination no longer works in the "normal" view.  I can use CTRL-ENTER instead, but then I need to manually advance to the next cell.

**Comment by damianavila** [comment]
@ijstokes can you try pulling from master again... I have just tested from master and I can not see this issue with the latest notebook.

**Comment by ijstokes** [comment]
OK, I now have the RISE icon in Jupyter twice, but having reinstalled from master the SHIFT-ENTER problem seems to be solved.  Perhaps I failed to pull the updates from master before installing.  I'll let you know if the problem comes up again.  I'm starting to use RISE more, so I'll notice!

**Comment by damianavila** [comment]
Nice, thanks for trying again. I should a beta soon for the next release. I will let you know :wink:
